import type { Subject } from "./types";

/**
 * Curated GCSE specification data. Reconstructed from the original app and
 * extended. Users can request additional subjects via the in-app request form
 * (written to the `spec_requests` Firestore collection).
 */
export const SUBJECTS: Subject[] = [
  {
    id: "maths",
    name: "Maths",
    board: "Edexcel",
    color: "#10b981",
    emoji: "📐",
    topics: [
      { id: "m1", name: "Number", subtopics: ["Types of number & BIDMAS", "Fractions, decimals & percentages", "Powers, roots & surds", "Standard form", "Bounds & error intervals", "Ratio & proportion"] },
      { id: "m2", name: "Algebra", subtopics: ["Simplifying & expanding", "Factorising", "Solving linear equations", "Solving quadratics", "Simultaneous equations", "Inequalities", "Sequences (nth term)", "Functions & composite functions", "Algebraic proof"] },
      { id: "m3", name: "Graphs", subtopics: ["Straight line graphs (y=mx+c)", "Quadratic & cubic graphs", "Reciprocal & exponential graphs", "Circle graphs", "Transformations of graphs", "Distance-time & velocity-time"] },
      { id: "m4", name: "Ratio, Proportion & Rates", subtopics: ["Direct & inverse proportion", "Speed, distance, time", "Density & pressure", "Percentage change & reverse %", "Growth & decay"] },
      { id: "m5", name: "Geometry & Measures", subtopics: ["Angles in polygons", "Circle theorems", "Area & perimeter", "Volume & surface area", "Pythagoras theorem", "Trigonometry (SOH CAH TOA)", "Sine & cosine rule", "Vectors", "Transformations", "Loci & constructions"] },
      { id: "m6", name: "Probability & Statistics", subtopics: ["Basic probability", "Tree diagrams", "Venn diagrams", "Frequency tables & averages", "Cumulative frequency & box plots", "Histograms", "Scatter graphs & correlation"] },
    ],
  },
  {
    id: "biology",
    name: "Biology",
    selectorName: "Triple Biology",
    board: "AQA",
    color: "#34d399",
    emoji: "🧬",
    topics: [
      { id: "b1", name: "Cell Biology", subtopics: ["Cell structure (prokaryotic/eukaryotic)", "Cell division (mitosis & meiosis)", "Cell transport (diffusion, osmosis, active transport)", "Stem cells", "Microscopy & cell size calculations"] },
      { id: "b2", name: "Organisation", subtopics: ["Digestive system & enzymes", "Heart & blood vessels", "Blood components", "Lungs & gas exchange", "Plant tissues & transport", "Transpiration"] },
      { id: "b3", name: "Infection & Response", subtopics: ["Pathogens & disease", "Immune response", "Vaccination", "Antibiotics & painkillers", "Drug development & testing"] },
      { id: "b4", name: "Bioenergetics", subtopics: ["Photosynthesis (equation & limiting factors)", "Aerobic respiration", "Anaerobic respiration", "Exercise & metabolism"] },
      { id: "b5", name: "Homeostasis & Response", subtopics: ["Nervous system (reflex arc)", "Brain structure", "Hormonal coordination", "Blood glucose regulation (diabetes)", "Thermoregulation", "Reproductive hormones & contraception"] },
      { id: "b6", name: "Inheritance & Evolution", subtopics: ["DNA structure & protein synthesis", "Genetic inheritance (Punnett squares)", "Mutations", "Natural selection & evolution", "Classification", "Extinction & biodiversity"] },
      { id: "b7", name: "Ecology", subtopics: ["Food chains & webs", "Sampling techniques", "Carbon cycle", "Water cycle", "Biodiversity & conservation", "Human impact on environment"] },
    ],
  },
  {
    id: "chemistry",
    name: "Chemistry",
    selectorName: "Triple Chemistry",
    board: "AQA",
    color: "#ef4444",
    emoji: "⚗️",
    topics: [
      { id: "c1", name: "Atomic Structure & the Periodic Table", subtopics: ["Atomic structure (protons, neutrons, electrons)", "Isotopes & relative atomic mass", "Development of the periodic table", "Electronic configuration", "Metals & non-metals", "Group 0, 1 & 7 properties", "Transition metals"] },
      { id: "c2", name: "Bonding, Structure & Properties", subtopics: ["Ionic bonding & structure", "Covalent bonding (simple & giant)", "Metallic bonding", "Allotropes of carbon", "Polymers", "Nanoparticles"] },
      { id: "c3", name: "Quantitative Chemistry", subtopics: ["Conservation of mass", "Relative formula mass", "Moles", "Balancing equations", "Percentage yield", "Atom economy", "Concentration calculations"] },
      { id: "c4", name: "Chemical Changes", subtopics: ["Reactivity series", "Extraction of metals", "Oxidation & reduction", "Electrolysis", "Acids & alkalis (pH, neutralisation)", "Reactions of acids (salts production)", "Strong vs weak acids"] },
      { id: "c5", name: "Energy Changes", subtopics: ["Exothermic & endothermic reactions", "Bond energies & calculations", "Reaction profiles", "Hydrogen fuel cells"] },
      { id: "c6", name: "Rate & Extent of Reaction", subtopics: ["Factors affecting rate", "Collision theory", "Reversible reactions & equilibrium", "Le Chatelier's principle"] },
      { id: "c7", name: "Organic Chemistry", subtopics: ["Crude oil & hydrocarbons", "Alkanes & combustion", "Cracking", "Alkenes & addition reactions", "Polymers", "Alcohols & carboxylic acids"] },
      { id: "c8", name: "Chemical Analysis", subtopics: ["Purity & formulations", "Chromatography (Rf values)", "Flame tests", "Tests for gases & ions"] },
      { id: "c9", name: "Chemistry of the Atmosphere", subtopics: ["Evolution of the atmosphere", "Greenhouse gases & climate change", "Atmospheric pollutants"] },
      { id: "c10", name: "Using Resources", subtopics: ["Finite & renewable resources", "Potable water treatment", "Lifecycle assessment", "Corrosion & alloys", "The Haber process & NPK fertilisers"] },
    ],
  },
  {
    id: "physics",
    name: "Physics",
    selectorName: "Triple Physics",
    board: "AQA",
    color: "#6366f1",
    emoji: "⚡",
    topics: [
      { id: "p1", name: "Energy", subtopics: ["Energy stores & transfers", "Conservation of energy", "Kinetic & potential energy calculations", "Specific heat capacity", "Power & efficiency", "Renewable & non-renewable energy sources"] },
      { id: "p2", name: "Electricity", subtopics: ["Circuit symbols & diagrams", "Series & parallel circuits", "Ohm's law & resistance", "I-V characteristics", "Mains electricity & AC/DC", "Power & energy calculations", "Static electricity"] },
      { id: "p3", name: "Particle Model of Matter", subtopics: ["States of matter & particle model", "Density calculations", "Internal energy & temperature", "Specific latent heat", "Gas pressure & temperature"] },
      { id: "p4", name: "Atomic Structure", subtopics: ["Atomic structure & nuclear model", "Radioactive decay (alpha, beta, gamma)", "Half-life calculations", "Background radiation", "Fission & fusion", "Uses & dangers of radiation"] },
      { id: "p5", name: "Forces", subtopics: ["Contact & non-contact forces", "Resultant forces & free body diagrams", "Newton's 3 laws", "Momentum & conservation", "Work done & energy", "Stretching: Hooke's law", "Pressure in fluids", "Moments & levers"] },
      { id: "p6", name: "Waves", subtopics: ["Transverse & longitudinal waves", "Wave calculations (v=f×λ)", "Reflection, refraction & EM spectrum", "Sound waves", "Colour & light", "Black body radiation"] },
      { id: "p7", name: "Magnetism & Electromagnetism", subtopics: ["Magnets & magnetic fields", "Electromagnetism (motor effect)", "Fleming's left-hand rule", "Induced potential & generators", "Transformers & the National Grid"] },
    ],
  },
  {
    id: "english",
    name: "English",
    board: "AQA",
    color: "#a78bfa",
    emoji: "📚",
    topics: [
      { id: "en1", name: "Language Paper 1 — Imaginative Writing", subtopics: ["Reading: Source analysis (structure & language)", "Q2 — Language analysis (methods & effects)", "Q3 — Structure analysis", "Q4 — Evaluation", "Q5 — Creative writing (narrative)", "Q5 — Creative writing (description)"] },
      { id: "en2", name: "Language Paper 2 — Writers' Viewpoints", subtopics: ["Reading: Two non-fiction sources", "Q1 — True/false identification", "Q2 — Summary & synthesis", "Q3 — Language analysis (non-fiction)", "Q4 — Comparing writers' perspectives", "Q5 — Non-fiction writing (article/letter/speech)"] },
      { id: "en3", name: "Literature: Macbeth", subtopics: ["Plot overview & timeline", "Macbeth's character arc", "Lady Macbeth & power", "Themes: ambition, guilt, fate", "Key quotations (with context)", "Context: Jacobean era & divine right"] },
      { id: "en4", name: "Literature: A Christmas Carol", subtopics: ["Scrooge's transformation", "The Ghosts (symbolism & purpose)", "Themes: poverty, redemption, Christmas", "Key quotations", "Context: Victorian England & social reform"] },
      { id: "en5", name: "Literature: Power & Conflict Poetry", subtopics: ["Ozymandias", "London", "The Prelude", "My Last Duchess", "Charge of the Light Brigade", "Exposure", "Storm on the Island", "Bayonet Charge", "Remains", "Poppies", "War Photographer", "Tissue", "The Emigree", "Checking Out Me History", "Kamikaze", "Unseen poetry techniques"] },
      { id: "en6", name: "Literature: An Inspector Calls", subtopics: ["Plot & structure", "Character analysis", "Themes: responsibility, class, age", "Key quotations", "Context: 1912 vs 1945 staging", "Priestley's message"] },
    ],
  },
  {
    id: "rs",
    name: "Religious Studies",
    board: "Eduqas",
    color: "#f59e0b",
    emoji: "✝️",
    topics: [
      { id: "rs1", name: "Christianity: Beliefs & Teachings", subtopics: ["Nature of God (omnipotent, benevolent, omniscient)", "The Trinity", "Creation", "Incarnation & Jesus's nature", "Salvation & atonement", "Life after death (Heaven, Hell, Purgatory)", "The afterlife & resurrection"] },
      { id: "rs2", name: "Christianity: Practices", subtopics: ["Worship (liturgical & non-liturgical)", "Prayer & the Lord's Prayer", "Sacraments (Baptism & Eucharist)", "Pilgrimage", "The Church's role in the local community", "Church & worldwide Church (food banks etc.)", "Festivals: Christmas & Easter"] },
      { id: "rs3", name: "Islam: Beliefs & Teachings", subtopics: ["Nature of Allah (Tawhid)", "The Six Beliefs (Sunni)", "Five Roots of Usul ad-Din (Shia)", "Prophethood (Risalah) & Muhammad", "Holy Books (Quran & others)", "Angels", "Akhirah (life after death)", "Predestination (Al-Qadr)"] },
      { id: "rs4", name: "Islam: Practices", subtopics: ["Five Pillars: Shahadah, Salah, Sawm, Zakah, Hajj", "Jihad (greater & lesser)", "Festivals: Id-ul-Adha & Id-ul-Fitr", "10 Obligatory Acts (Shia)"] },
      { id: "rs5", name: "Religion, Peace & Conflict", subtopics: ["Just War theory", "Holy War & pacifism", "Weapons of mass destruction", "Victims of war & forgiveness", "Christian & Muslim views on war", "Terrorism & religion"] },
      { id: "rs6", name: "Religion, Life & Death", subtopics: ["Origin of the universe (Big Bang & creation)", "Value of the world & stewardship", "Origins of human life", "Abortion", "Euthanasia", "Death & afterlife beliefs (Christian & Muslim)"] },
    ],
  },
  {
    id: "history",
    name: "History",
    board: "Edexcel",
    color: "#818cf8",
    emoji: "🏛️",
    topics: [
      { id: "h1", name: "Weimar & Nazi Germany", subtopics: ["The Weimar Republic & constitution", "Problems 1919–23 (Treaty of Versailles, hyperinflation)", "Recovery: Stresemann & the Golden Years", "Hitler's rise to power 1929–33", "Nazi dictatorship & control", "Life in Nazi Germany"] },
      { id: "h2", name: "Conflict in Asia", subtopics: ["Second World War in Asia", "The atomic bombs & surrender of Japan", "The Korean War", "The Vietnam War", "Cold War tensions in Asia"] },
      { id: "h3", name: "Superpower Relations & the Cold War", subtopics: ["Origins of the Cold War 1941–58", "Berlin crises (1948–49, 1961)", "The Cuban Missile Crisis", "Czechoslovakia 1968", "Detente & the end of the Cold War"] },
      { id: "h4", name: "Medicine Through Time", subtopics: ["Medieval medicine", "Renaissance & the Scientific Revolution", "Germ theory (Pasteur & Koch)", "Public health & Florence Nightingale", "20th century medicine (penicillin, NHS)", "Surgery & anaesthetics"] },
      { id: "h5", name: "Exam Skills", subtopics: ["Source analysis (comprehension & utility)", "Interpretation questions", "Explain / describe questions", "Narrative account & consequence questions", "Judgement essays", "Revision of key dates"] },
    ],
  },
  {
    id: "german",
    name: "German",
    board: "AQA",
    color: "#fb923c",
    emoji: "🇩🇪",
    topics: [
      { id: "g1", name: "Identity & Culture", subtopics: ["Family relationships & marriage", "Friendships", "Social media & technology", "Free time: sport & music", "Customs & festivals", "Food & daily routine"] },
      { id: "g2", name: "Local, National & Global", subtopics: ["Local area & environment", "Describing your town", "Healthy & unhealthy living", "Poverty & homelessness", "Global issues (environment, Fairtrade)", "Weather & the natural world"] },
      { id: "g3", name: "Current & Future Study / Employment", subtopics: ["School subjects & opinions", "Rules & uniform", "Work experience", "Career aspirations", "Applying for jobs", "Advantages of language learning"] },
      { id: "g4", name: "Grammar", subtopics: ["Nouns, gender & plurals", "Cases: Nominative, Accusative, Dative, Genitive", "Adjective endings", "Pronouns", "Present tense (regular & irregular)", "Past tense: Perfekt", "Past tense: Imperfekt", "Future tense", "Conditional", "Modal verbs", "Word order (V2, subordinate clauses)", "Negatives (nicht & kein)"] },
      { id: "g5", name: "Skills", subtopics: ["Listening exam technique", "Reading comprehension strategies", "Writing: structured responses", "Speaking: role play preparation", "Speaking: photo card technique", "Translation (German to English & English to German)"] },
    ],
  },
  {
    id: "french",
    name: "French",
    board: "AQA",
    color: "#38bdf8",
    emoji: "🇫🇷",
    topics: [
      { id: "f1", name: "Identity & Culture", subtopics: ["Family & relationships", "Friendships", "Social media & technology", "Free time, sport & hobbies", "Customs & festivals", "Food & drink"] },
      { id: "f2", name: "Local, National & Global", subtopics: ["Home, town & local area", "Charity & voluntary work", "Healthy & unhealthy living", "Environment & global issues", "Poverty & homelessness"] },
      { id: "f3", name: "Current & Future Study / Employment", subtopics: ["School subjects & opinions", "School rules & uniform", "Post-16 education", "Jobs & career ambitions", "The importance of languages"] },
      { id: "f4", name: "Grammar", subtopics: ["Nouns, gender & articles", "Present tense (regular & irregular)", "Perfect tense (avoir & être)", "Imperfect tense", "Future tense (near & simple)", "Conditional", "Reflexive verbs", "Modal verbs", "Negatives (ne…pas)", "Adjectives & agreements"] },
      { id: "f5", name: "Skills", subtopics: ["Listening technique", "Reading strategies", "Writing: structured answers", "Speaking: role play & photo card", "General conversation", "Translation"] },
    ],
  },
  {
    id: "spanish",
    name: "Spanish",
    board: "AQA",
    color: "#f97316",
    emoji: "🇪🇸",
    topics: [
      { id: "sp1", name: "Identity & Culture", subtopics: ["Family, relationships & marriage", "Friendships & role models", "Social media & technology", "Free time: sport, music & going out", "Healthy vs unhealthy lifestyles", "Customs, festivals & food culture"] },
      { id: "sp2", name: "Local, National & Global", subtopics: ["Home, town & local area", "Urban vs rural life & the environment", "Charity & voluntary work", "Global issues (the environment)", "Poverty & homelessness"] },
      { id: "sp3", name: "Current & Future Study / Employment", subtopics: ["School subjects & opinions", "School rules & uniform", "Post-16 study", "Career choices & ambitions", "The value of learning languages"] },
      { id: "sp4", name: "Grammar", subtopics: ["Nouns, gender & articles", "Present tense (regular & irregular)", "Two past tenses (preterite & imperfect)", "Future tense", "Conditional", "Reflexive verbs", "Radical-changing verbs", "Modal verbs", "Negatives", "Adjective agreements"] },
      { id: "sp5", name: "Skills", subtopics: ["Listening technique", "Reading strategies", "Writing: structured responses", "Speaking: role play & photo card", "General conversation", "Translation"] },
    ],
  },
  {
    id: "geography",
    name: "Geography",
    board: "AQA",
    color: "#2dd4bf",
    emoji: "🌍",
    topics: [
      { id: "geo1", name: "The Challenge of Natural Hazards", subtopics: ["Tectonic hazards (earthquakes & volcanoes)", "Plate boundaries & case studies", "Weather hazards (tropical storms)", "UK extreme weather", "Climate change: evidence & causes", "Climate change: effects & responses"] },
      { id: "geo2", name: "The Living World", subtopics: ["Ecosystems (small scale & global)", "Tropical rainforests: structure & biodiversity", "Tropical rainforests: deforestation & management", "Hot deserts: characteristics & adaptations", "Hot deserts: opportunities & challenges"] },
      { id: "geo3", name: "Physical Landscapes in the UK", subtopics: ["Coastal processes (erosion, deposition, transportation)", "Coastal landforms", "Coastal management", "River processes & landforms", "Flood management"] },
      { id: "geo4", name: "Urban Issues & Challenges", subtopics: ["Global urban growth & urbanisation", "Megacities", "Case study: LIC/NEE city (e.g. Rio)", "Case study: UK city (e.g. Bristol)", "Urban sustainability"] },
      { id: "geo5", name: "The Changing Economic World", subtopics: ["Development gap: indicators (HDI, GNI)", "Causes of uneven development", "Strategies to reduce the gap", "NEE case study (e.g. Nigeria)", "Economic change in the UK", "UK post-industrial economy"] },
      { id: "geo6", name: "The Challenge of Resource Management", subtopics: ["Global resource management (food, water, energy)", "Food in the UK & food security", "Water in the UK & global water stress", "Energy in the UK & energy security", "Case study: large-scale energy scheme"] },
      { id: "geo7", name: "Geographical Skills & Fieldwork", subtopics: ["Atlas & map skills", "OS map reading", "Graph & statistical skills", "Fieldwork: physical environment", "Fieldwork: human environment", "Evaluating geographical data"] },
    ],
  },
  {
    id: "cs",
    name: "Computer Science",
    board: "OCR",
    color: "#e879f9",
    emoji: "💻",
    topics: [
      { id: "cs1", name: "Fundamentals of Algorithms", subtopics: ["Computational thinking (abstraction, decomposition, pattern recognition)", "Algorithm design & representation (pseudocode, flowcharts)", "Searching algorithms (linear, binary)", "Sorting algorithms (bubble, merge, insertion)", "Standard algorithms (reverse, factorial)", "Trace tables & correctness"] },
      { id: "cs2", name: "Programming Concepts", subtopics: ["Variables, constants & data types (int, float, boolean, string)", "Operators (arithmetic, logical, comparison)", "Selection (if/else, switch)", "Iteration (for, while, do-while)", "Subroutines (functions, procedures)", "Parameter passing (by value, by reference)", "Local & global scope", "Modules & libraries"] },
      { id: "cs3", name: "Data Structures", subtopics: ["Arrays (1D & 2D)", "Records (structs)", "Stacks (LIFO & operations)", "Queues (FIFO & operations)", "Graphs (nodes, edges, weighted)", "Trees (nodes, leaves, root)", "Hash tables & hashing"] },
      { id: "cs4", name: "Network Concepts", subtopics: ["Computer networks (LAN, WAN)", "Internet protocols (TCP/IP, DNS)", "Network topologies (star, mesh, bus)", "Cybersecurity (hacking, malware, encryption)", "Network security (firewalls, user access controls)"] },
      { id: "cs5", name: "Hardware & Software", subtopics: ["CPU (control unit, ALU, registers)", "Cache memory", "RAM & ROM", "Virtual memory", "Operating systems (functions & features)", "System software (BIOS, device drivers)", "Application software"] },
      { id: "cs6", name: "Data Representation", subtopics: ["Binary, denary & hexadecimal conversion", "Binary addition & subtraction", "Character encoding (ASCII, Unicode)", "Image representation (bitmap, vector, compression)", "Audio representation (sampling, bit depth)", "Video compression techniques"] },
      { id: "cs7", name: "Databases", subtopics: ["Database concepts (tables, records, fields)", "Flat-file vs relational databases", "Primary & foreign keys", "SQL SELECT, INSERT, UPDATE, DELETE", "JOIN operations", "Normalisation (1NF, 2NF, 3NF)"] },
    ],
  },
  {
    id: "music",
    name: "Music",
    board: "Edexcel",
    color: "#f472b6",
    emoji: "🎵",
    topics: [
      { id: "mu1", name: "Instrumental Music 1700–1820", subtopics: ["Baroque concerto grosso", "Classical symphony & sonata form", "Romantic piano music", "Set work: Brandenburg Concerto (Bach)", "Set work: Symphony No.40 (Mozart)", "Set work: Piano Sonata No.8 (Beethoven)"] },
      { id: "mu2", name: "Vocal Music", subtopics: ["Music for voice (solo & ensemble)", "Opera & oratorio", "Set work: Defying Gravity (Wicked)", "Set work: Mozart's Die Zauberflöte", "Set work: Bach's cantata", "Vocal techniques & texture"] },
      { id: "mu3", name: "Music for Stage & Screen", subtopics: ["Film music techniques", "Music theatre development", "Set work: Star Wars (John Williams)", "Set work: Main Title from Batman", "Leitmotif & underscore", "Music & narrative"] },
      { id: "mu4", name: "Fusions", subtopics: ["Blues & jazz origins", "Fusion genres (jazz-funk, Afrobeat etc.)", "Set work: All Blues (Miles Davis)", "Set work: Grace (Jeff Buckley)", "Cross-cultural influences", "Electric & electronic instruments"] },
      { id: "mu5", name: "Musical Elements & Notation", subtopics: ["Melody, rhythm & metre", "Harmony & tonality", "Texture & structure", "Timbre & dynamics", "Reading & writing staff notation", "Identifying musical devices"] },
      { id: "mu6", name: "Listening & Appraising", subtopics: ["Unfamiliar piece analysis", "Comparing pieces", "Using musical vocabulary", "Identifying instruments", "Describing context & style", "Exam technique & past papers"] },
    ],
  },
  {
    id: "business",
    name: "Business",
    board: "Edexcel",
    color: "#facc15",
    emoji: "📈",
    topics: [
      { id: "bus1", name: "Enterprise & Entrepreneurship", subtopics: ["The role of business & enterprise", "Risk & reward", "Business aims & objectives", "Spotting a gap in the market", "Market research (primary & secondary)", "Market mapping"] },
      { id: "bus2", name: "Setting Up a Business", subtopics: ["Business ownership (sole trader, partnership, LTD, PLC)", "Franchising", "Location decisions", "Marketing mix (4 Ps)", "Business plans"] },
      { id: "bus3", name: "Finance", subtopics: ["Costs, revenue & profit", "Break-even analysis", "Cash flow forecasts", "Sources of finance", "Financial documents & terms"] },
      { id: "bus4", name: "Growing a Business", subtopics: ["Methods of growth", "Changes in marketing", "Product portfolio & the product life cycle", "Managing people & organisational structure", "Global markets & ethics"] },
    ],
  },
  {
    id: "pe",
    name: "Physical Education",
    board: "AQA",
    color: "#22d3ee",
    emoji: "🏃",
    topics: [
      { id: "pe1", name: "Applied Anatomy & Physiology", subtopics: ["The skeletal system", "The muscular system", "The respiratory system", "The cardiovascular system", "Aerobic & anaerobic exercise", "Effects of exercise"] },
      { id: "pe2", name: "Movement Analysis & Training", subtopics: ["Levers & planes of movement", "Components of fitness", "Principles of training (FITT, SPORT)", "Training methods", "Preventing injury"] },
      { id: "pe3", name: "Sport Psychology", subtopics: ["Skill & ability", "Goal setting (SMART)", "Information processing & guidance", "Feedback", "Arousal & aggression", "Motivation & personality"] },
      { id: "pe4", name: "Socio-Cultural Influences", subtopics: ["Engagement patterns of social groups", "Commercialisation of sport", "Ethics & deviance in sport", "Technology in sport"] },
    ],
  },
];
